language: java
sudo: true
dist: trusty
jdk: oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install:
  - chmod +x mvnw

notifications:
  email:
    recipients:
      - rvalentim@unilurio.ac.mz
      - guerzeneldo@gmail.com
      - felerminoali@gmail.com
    on_success: always # default: change
    on_failure: always # default: always

after_success:
  - mvn clean test jacoco:report coveralls:report